apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud.fullname" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nextcloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nextcloud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "nextcloud.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            # Determine which secret to use. If an existing one is provided, use it.
            # Otherwise, use the one created by this chart.
            {{- $secretName := "" }}
            {{- if .Values.database.existingSecret }}
            {{- $secretName = .Values.database.existingSecret }}
            {{- else }}
            {{- $secretName = printf "%s-db" (include "nextcloud.fullname" .) }}
            {{- end }}
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: POSTGRES_PASSWORD
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: NEXTCLOUD_ADMIN_USER
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: NEXTCLOUD_ADMIN_PASSWORD
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
            - name: nextcloud-config
              mountPath: /var/www/html/config/autoconfig.php
              subPath: nextcloud-config.php
      volumes:
        - name: nextcloud-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "nextcloud.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: nextcloud-config
          configMap:
            name: {{ include "nextcloud.fullname" . }}-config