{{- if and .Values.database.enabled (not .Values.database.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud.fullname" . }}-db
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
type: Opaque
data:
  # General Nextcloud Admin Credentials
  NEXTCLOUD_ADMIN_USER: {{ .Values.nextcloud.admin.user | b64enc | quote }}
  NEXTCLOUD_ADMIN_PASSWORD: {{ .Values.nextcloud.admin.password | b64enc | quote }}

  # Database Credentials
  POSTGRES_HOST: {{ .Values.database.host | b64enc | quote }}
  POSTGRES_USER: {{ .Values.database.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.database.database | b64enc | quote }}
{{- end -}}