apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce # Standard for EBS
  storageClassName: ebs-sc
  
  resources:
    requests:
      storage: 10Gi