apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
  namespace: default
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:latest # Using the official image as requested
          ports:
            - containerPort: 80
          env:
            # These environment variables configure Nextcloud to use our external PostgreSQL database.
            # The values are pulled securely from the Secret we created earlier.
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: POSTGRES_PASSWORD
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: NEXTCLOUD_ADMIN_USER
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: NEXTCLOUD_ADMIN_PASSWORD
          volumeMounts:
            # We are mounting the persistent volume at this path inside the container.
            # This is where Nextcloud stores all its data (user files, configs, etc.).
            - name: nextcloud-data
              mountPath: /var/www/html
      volumes:
        # This links the volumeMount above to the PersistentVolumeClaim.
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc